# Generated by Django 5.0.4 on 2024-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
