# Generated by Django 5.0.4 on 2024-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_alter_applicant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='overall_experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='ats.keyword'),
        ),
    ]
