# Generated by Django 5.0.4 on 2024-04-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_keyword_applicant_cgpa_applicant_overall_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='overall_experience',
        ),
        migrations.AddField(
            model_name='applicant',
            name='exp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
