# Generated by Django 5.0.4 on 2024-04-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_remove_applicant_overall_experience_applicant_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='exp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
