# Generated by Django 5.0.4 on 2024-04-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('exp', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('resume', models.FileField(null=True, upload_to='resumes/')),
                ('jd', models.IntegerField(null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='ats.keyword')),
            ],
        ),
    ]
