# Generated by Django 4.1.13 on 2024-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_alter_applicant_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='jd',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='keywords',
        ),
        migrations.AddField(
            model_name='applicant',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
